### ISSUE TITLE
Deploy to github pages

### ISSUE THREAD

**Issue by CodeF53** [Awish-Senpai/ForgottenKeep#5]
Deploying to github pages would allow people to install this theme by adding one line to their custom css:
```css
/* Forgotten Keep */
@import url('https://awish-senpai.github.io/ForgottenKeep/index.css')
```

Deploying to pages is super easy:
1. go to the [the pages settings of this github repo](https://github.com/Awish-Senpai/personal-site/settings/pages) 
      ![](https://i.imgur.com/m27J2GT.png)
2. change Branch from None to Main
3. click Save
      ![](https://i.imgur.com/K6g1HKu.png)

**Comment by Kyiro** [comment]
Vouch

**Comment by Anish-530** [comment]
Thanks for this. Changed the settings as mentioned by you :). Good day!
